let currentSection = "corners";

const corners = {
  "BA":	"[R2,D' L2 D]",
  "BC":	"x R':[U,R' D2 R]",
  "BD":	"A PERM",
  "BE":	"D':[R2,D' L2 D]",
  "BF":	"F x R':[U,R' D2 R]",
  "BG":	"U2':[R' D R,U']",
  "BH":	"[U,R D' R']",
  "BI":	"x:[U R' U',L]",
  "BJ":	"x:[R',U' L U]",
  "BK":	"[L' D2 L,U']",
  "BL":	"[U,R D2 R']",
  "BM":	"U R:[R D R',U2]",	
  "BO":	"[U,R D R']",
  "BP":	"U':[L D' L',U']",
  "BX":	"D:[D R2 D',L2]",
  "BS":	"D':[U,R D R']",
  "BT":	"y:[U,R' D' R]",
  "BU":	"R:[L2,U R' U']",
  
  "CA":	"PER SPECIALS",
  "CB":	"l':[R' D2 R,U]",
  "CD":	"A9",
  "CE":	"R D' R':[U2,R' D R]",
  "CF":	"F:[R' D' R,U2]",
  "CG":	"[U2,R' D R]",
  "CH":	"[L' D' L,U2]",
  "CI":	"L':[R' D2 R,U2]",
  "CK":	"[L' D2 L,U2]",
  "CL":	"D:[U2,R' D' R]",
  "CN":	"F:[R2,U' L' U]",
  "CO":	"[L' D L,U2]",
  "CP":	"[U2,R' D' R]",
  "CQ":	"R':[U2,L' D2 L]",
  "CX":	"D2:[PER SPECIALS]",
  "CS":	"[U2,R' D2 R]",
  "CT":	"D':[U2,R' D' R]",
  "CU":	"R U2 R:[R D2 R',U2]",
  
  "DA":	"x':[L' U' L,D2]",
  "DB":	"x L:[U',L D2 L']",
  "DC":	"A9",
  "DE":	"x:[D2,L U L']",
  "DG":	"[U',L D L']",
  "DH":	"[L' D' L,U]",
  "DJ":	"R:[A9]",
  "DK":	"[L' D2 L,U]",
  "DL":	"y':[L D' L',U]",
  "DM":	"x':[D,R U' R']",
  "DN":	"x':[R' D R,U']",
  "DO":	"[L' D L,U]",
  "DP":	"[U',L D' L']",
  "DQ":	"L:[U2,L D L']",
  "DX":	"U':[D' R2 D,L2]",
  "DS":	"y':[L D L',U]",
  "DT":	"[U',L D2 L']",
  "DU":	"U:[L2,D R2 D']",

  "FA":	"F:[U2,R' D R]",
  "FB":	"U R':[R' D' R,U2]",
  "FC":	"F:[U2,R' D' R]",
  "FE":	"R U R' U':[R D R',U2]",
  "FG":	"U' R U':[R' D R,U2]",
  "FH":	"F:[L' D' L,U2]",
  "FJ":	"F:[L' D2 L,U2]",
  "FK":	"R F:[U2,R' D' R]",
  "FL":	"U' R:[U2,R D2 R']",
  "FM":	"R U R' U' D:[R D R',U2]",
  "FN":	"B' :[R D R',U2]",
  "FO":	"F:[L' D L,U2]",
  "FP":	"R2 B' :[R D R',U2]",
  "FQ":	"R' F:[U2,R' D' R]",
  "FX":	"R U R' U' D':[R D R',U2]",
  "FS":	"F:[U2,R' D2 R]",
  "FT":	"y L:[U2,L D' L']",
  "FU":	"F2:[R' D' R,U2]",

  "GA":	"R2:[GUN K]",
  "GB":	"U:[R' D R,U]",
  "GC":	"[R' D R,U2]",
  "GD":	"[L D L',U']",
  "GE":	"R2:[R' D R,U2]",
  "GF":	"F:[A9]",
  "GH":	"D':[U R' U',L]",
  "GI":	"U:[L2,U R U']",
  "GJ":	"F:[L' D2 L,U]",
  "GK":	"[D,R U2 R']",
  "GM":	"x':[D2,R U' R']",
  "GN":	"x':[R' D2 R,U']",
  "GO":	"D:[R U2 R',D2]",
  "GP":	"R' y':[R U' R',D2]",
  "GQ":	"R':[R' D R,U2]",
  "GX":	"D' R:[D2,R U2 R']",
  "GS":	"y':[R U' R',D]",
  "GT":	"F:[U',L D2 L']",
  
  "HA":	"R':[D',R' U R]",
  "HB":	"[R D' R',U]",
  "HC":	"[U2,L' D' L]",
  "HD":	"[U,L' D' L]",
  "HE":	"R2:[U2,L' D' L]",
  "HF":	"F:[U2,L' D' L]",
  "HG":	"F:[U,L' D' L]",
  "HI":	"F R:[R D' R',U]",
  "HJ":	"R:[R D' R',U]",
  "HK":	"[L F2 L',B']",
  "HL":	"F':[L F2 L',B']",
  "HM":	"R' D':[R' U R,D2]",
  "HN":	"R2 D':[R' U R,D2]",
  "HO":	"R:[L U L',D2]",
  "HP":	"[L U L',D2]",
  "HQ":	"R':[U2,L' D' L]",
  "HT":	"[D',R' U R]",
  "HU":	"F':[L U L',D2]",

  "IA":	"[U R2 U',L']",
  "IB":	"x:[L,U R' U']",
  "IC":	"L':[U2,R' D2 R]",
  "IE":	"x:[R U2 R',D2]",
  "IG":	"U:[U R U',L2]",
  "IH":	"F R:[U,R D' R']",
  "IJ":	"z:[U,R' D' R]",
  "IK":	"x:[U2,R' D2 R]",
  "IL":	"D z:[U,R' D R,]",
  "IM":	"x':[U' R U,L']",
  "IN":	"[U R U',L']",
  "IO":	"[L,U' R2 U]",
  "IP":	"[L,U' R U]",
  "IQ":	"L:[R D2 R',U2]",
  "IX":	"D2[U R2 U',L']",
  "IS":	"D':[L,U' R2 U]",
  "IT":	"[U R' U',L']",
  "IU":	"D:[U R2 U',L']",

  "JA":	"z':[U',R' D2 R]",
  "JB":	"x:[U' L U,R']",
  "JD":	"R:[A9]",
  "JE":	"x:[D2,L U' L']",
  "JF":	"F:[U2,L' D2 L]",
  "JG":	"F:[U,L' D2 L]",
  "JH":	"R:[U,R D' R']",
  "JI":	"z:[R' D' R,U]",
  "JK":	"x:[U,R' D2 R]",
  "JL":	"R:[U,R D2 R']",
  "JN":	"R:[U,R D R']",
  "JO":	"F:[R U2 R',D']",
  "JP":	"D2 R:[U,R D' R']",
  "JQ":	"R':[PER SPECIALS]",
  "JX":	"z' R:[R U' R',D2]",
  "JS":	"F:[R U2 R',D2]",
  "JT":	"x:[U' L U,R2]",
  "JU":	"[D R' D',L2]",

  "KB":	"y:[R' D R,U]",
  "KC":	"[U2,L' D2 L]",
  "KD":	"[U,L' D2 L]",
  "KE":	"x:[D2,L U2 L']",
  "KF":	"R F:[R' D' R,U2]",
  "KG":	"[R U2 R',D]",
  "KH":	"R U:[R D' R',U2]",
  "KI":	"x:[R' D2 R,U2]",
  "KJ":	"x:[R' D2 R,U]",
  "KL":	"x:[R' D2 R,U']",
  "KM":	"z' R:[R D' R',U2]",
  "KN":	"x':[U,L D2 L']",
  "KO":	"[R U2 R',D']",
  "KQ":	"D' R':[R' D R,U2]",
  "KX":	"U':[L2,U' R U]",
  "KS":	"[R U2 R',D2]",
  "KT":	"F:[D2,R' U R]",
  "KU":	"U L:[D2,L U' L']",

  "LA":	"R':[D2,R' U R]",
  "LB":	"[R D2 R',U]",
  "LC":	"D:[R' D' R,U2]",
  "LD":	"y':[R' D' R,U']",
  "LE":	"x:[R U' R',D2]",
  "LF":	"U' R:[R D2 R',U2]",
  "LH":	"D':[D',R' U R]",
  "LI":	"D z:[R' D R,U]",
  "LJ":	"R:[R D2 R',U]",
  "LK":	"x:[U',R' D2 R]",
  "LM":	"R' D:[D,R' U R]",
  "LN":	"D:[R2,U' L' U]",
  "LO":	"F':[R U2 R',D']",
  "LP":	"y':[D,R' U2 R]",
  "LQ":	"L:[R D' R',U2]",
  "LX":	"z' R:[R U R',D2]",
  "LS":	"F':[R U2 R',D2]",
  "LT":	"[D2,R' U R]",

  "MA":	"x':[R U' R',D']",
  "MB":	"U R:[U2,R D R']",
  "MD":	"x':[R U' R',D]",
  "ME":	"R U R' U':[D,R' U' R]",
  "MF":	"R U R' U' D:[U2,R D R']",
  "MG":	"x':[R U' R',D2]",
  "MH":	"R':[D2,L U L']",
  "MI":	"x':[L',U' R U]",
  "MK":	"z' R:[U2,R D' R']",
  "ML":	"R' D:[R' U R,D]",
  "MN":	"[R,U' L' U]",
  "MO":	"z':[U2,R D' R']",
  "MP":	"x:[R',U L2 U']",
  "MQ":	"R':[R' D' R,U2]",
  "MX":	"U x:[D2,R' U R]",
  "MS":	"[D' R2 D,L']",
  "MT":	"R':[GUN, K]",
  "MU":	"x':[L2,U' R U]",

  "NA":	"D':[L2,U R U']",
  "NC":	"F:[U' L' U,R2]",
  "ND":	"x':[U',R' D R]",
  "NE":	"R:[D',R U2 R']",
  "NF":	"B':[U2,R D R']",
  "NG":	"x':[U',R' D2 R]",
  "NH":	"R2 D:[R' U R,D2]",
  "NI":	"[L',U R U']",
  "NJ":	"R:[R D R',U]",
  "NK":	"x':[L D2 L',U]",
  "NL":	"D:[U' L' U,R2]",
  "NM":	"[U' L' U,R]",
  "NO":	"[U' L' U,R']",
  "NP":	"[U' L' U,R2]",
  "NX":	"D:[L2,U R U']",
  "NS":	"[L,U R U']",
  "NT":	"D':[U' L' U,R2]",
  "NU":	"z:[U2,R D R']",

  "OA":	"y' R:[D2,R U' R']",
  "OB":	"[R D R',U]",
  "OC":	"[U2,L' D L]",
  "OD":	"[U,L' D L]",
  "OF":	"F:[U2,L' D L]",
  "OG":	"D':[R U2 R',D2]",
  "OH":	"R:[D2,L U L']",
  "OI":	"[U' R2 U,L]",
  "OJ":	"F:[D',R U2 R']",
  "OK":	"[D',R U2 R']",
  "OL":	"F':[D',R U2 R']",
  "OM":	"z':[R D' R',U2]",
  "ON":	"[R',U' L' U]",
  "OP":	"z':[R D' R',U']",
  "OQ":	"D2 R':[R' D R,U2]",
  "OX":	"U R':[R' D2 R,U]",
  "OS":	"U:[R' U' R,D']",
  "OU":	"x:[U' R U,L2]",

  "PB":	"U:[R' D' R,U]",
  "PC":	"[R' D' R,U2]",
  "PD":	"[L D' L',U']",
  "PE":	"D' R':[D2,R' U R]",
  "PF":	"R2 B' :[U2,R D R']",
  "PG":	"R' y':[D2R U' R']",
  "PH":	"[D2,L U L']",
  "PI":	"[U' R U,L]",
  "PJ":	"D2 R:[R D' R',U]",
  "PL":	"y':[R' U2 R,D]",
  "PM":	"x:[U L2 U',R']",
  "PN":	"[R2,U' L' U]",
  "PO":	"z':[U',R D' R']",
  "PQ":	"R':[U2,L' D L]",
  "PX":	"D:[L2,U R' U']",
  "PS":	"x':[L,U' R2 U]",
  "PT":	"[D,R' U R]",
  "PU":	"z':[R U R',D2]",

  "QA":	"L:[L D' L',U2]",
  "QC":	"R':[L' D2 L,U2]",
  "QD":	"L:[L D L',U2]",
  "QE":	"L:[L D2 L',U2]",
  "QF":	"R' F:[R' D' R,U2]",
  "QG":	"R':[U2,R' D R]",
  "QH":	"R':[L' D' L,U2]",
  "QI":	"L:[U2,R D2 R']",
  "QJ":	"R':[PER SPECIALS]",
  "QK":	"D' R':[U2,R' D R]",
  "QL":	"L:[U2,R D' R']",
  "QM":	"R':[U2,R' D' R]",
  "QO":	"D2 R':[U2,R' D R]",
  "QP":	"R':[L' D L,U2]",
  "QX":	"U2 R:[R D' R',U2]",
  "QS":	"R':[U2,R' D2 R]",
  "QT":	"L:[U2,R D R']",
  "QU":	"D L:[L D' L',U2]",

  "SA":	"[U R2 U',L]",
  "SB":	"D':[R D R',U]",
  "SC":	"[R' D2 R,U2]",
  "SD":	"y':[U,L D L']",
  "SE":	"R:[D2,R U2 R']",
  "SF":	"F:[R' D2 R,U2]",
  "SG":	"y':[D,R U' R']",
  "SI":	"D':[U' R2 U,L]",
  "SJ":	"F:[D2,R U2 R']",
  "SK":	"[D2,R U2 R']",
  "SL":	"F':[D2,R U2 R']",
  "SM":	"x':[U' R U,L]",
  "SN":	"[U R U',L]",
  "SO":	"U:[D',R' U' R]",
  "SP":	"x':[U' R2 U,L]",
  "SQ":	"R':[R' D2 R,U2]",
  "ST":	"[U R' U',L]",
  "SU":	"U:[L',D R2 D']",

  "TA":	"z':[U,R' D2 R]",
  "TB":	"y:[R' D' R,U]",
  "TC":	"D':[R' D' R,U2]",
  "TD":	"[L D2 L',U']",
  "TF":	"F2:[R' U R,D]",
  "TG":	"F:[L D2 L',U']",
  "TH":	"[R' U R,D']",
  "TI":	"[L',U R' U']",
  "TJ":	"x:[R2,U' L U]",
  "TK":	"F:[R' U R,D2]",
  "TL":	"[R' U R,D2]",
  "TM":	"R':[GUN, K]",
  "TN":	"D':[R2,U' L' U]",
  "TP":	"[R' U R,D]",
  "TQ":	"L:[R D R',U2]",
  "TX":	"D2 R':[D2,R' U R]",
  "TS":	"[L,U R' U']",
  "TU":	"[L2,U R' U']",

  "UA":	"[U R2 U',L2]",
  "UB":	"R:[U R' U',L2]",
  "UC":	"R U2 R:[U2,R D2 R']",
  "UD":	"U:[D R2 D',L2]",
  "UE":	"R U R' U':[D2,R' U' R]",
  "UF":	"F2:[U2,R' D' R]",
  "UH":	"F':[D2,L U L']",
  "UI":	"D:[L',U R2 U']",
  "UJ":	"[L2,D R' D']",
  "UK":	"U L:[L U' L',D2]",
  "UM":	"x':[U' R U,L2]",
  "UN":	"[U R U',L2]",
  "UO":	"x:[L2,U' R U]",
  "UP":	"z':[D2,R U R']",
  "UQ":	"D L:[U2,L D' L']",
  "UX":	"D:[L2,U R2 U']",
  "US":	"F2:[U2, R' D2 R]",
  "UT":	"[U R' U',L2]",

  "AB":	"[D' L2 D,R2]",
  "AC":	"PER SPECIALS",
  "AD":	"x':[D2,L' U' L]",
  "AE":	"x:[R U R',D2]",
  "AF":	"F:[R' D R,U2]",
  "AG":	"R2:[GUN K]",
  "AH":	"R':[R' U R,D']",
  "AI":	"[L',U R2 U']",
  "AJ":	"z':[R' D2 R,U']",
  "AL":	"R':[R' U R,D2]",
  "AM":	"x':[D',R U' R']",
  "AN":	"D':[U R U',L2]",
  "AO":	"y' R:[R U' R',D2]",
  "AQ":	"L:[U2,L D' L']",
  "AX":	"R D:[D R' D',L2]",
  "AS":	"[L,U R2 U']",
  "AT":	"z':[R' D2 R,U]",
  "AU":	"[L2,U R2 U']",

  "EA":	"x:[D2,R U R']",
  "EB":	"D':[D' L2 D,R2]",
  "EC":	"R D' R':[R' D R,U2]",
  "ED":	"x:[L U L',D2]",
  "EF":	"R U R' U':[U2,R D R']",
  "EG":	"R:[R U2 R',D]",
  "EH":	"R2:[L' D' L,U2]",
  "EI":	"x:[D2,R U2 R']",
  "EJ":	"x:[L U' L',D2]",
  "EK":	"x:[L U2 L',D2]",
  "EL":	"x:[D2,R U' R']",
  "EM":	"R U R' U':[R' U' R,D]",
  "EN":	"R:[R U2 R',D']",
  "EP":	"D' R':[R' U R,D2]",
  "EQ":	"L:[U2,L D2 L']",
  "EX":	"D' x:[R U R',D2]",
  "ES":	"R:[R U2 R',D2]",
  "EU":	"R U R' U':[R' U' R,D2]",

  "XA":	"R D:[L2,D R' D']",
  "XB":	"D:[L2,D R2 D']",
  "XC":	"D2:[PER SPECIALS]",
  "XD":	"U':[L2,D' R2 D]",
  "XE":	"D' x:[D2,R U R']",
  "XF":	"R U R' U' D':[U2,R D R']",
  "XG":	"D' R:[R U2 R',D2]",
  "XI":	"D2[L',U R2 U']",
  "XJ":	"z' R:[D2,R U' R']",
  "XK":	"U':[U' R U,L2]",
  "XL":	"z' R:[D2,R U R']",
  "XM":	"U x:[R' U R,D2]",
  "XN":	"D:[U R U',L2]",
  "XO":	"U R':[U,R' D2 R]",
  "XP":	"D:[U R' U',L2]",
  "XQ":	"U2 R:[U2,R D' R']",
  "XT":	"D2 R':[R' U R,D2]",
  "XU":	"D:[U R2 U',L2]",
  
};

const edges = {
  "UL": "M2 U M2 U2 M2 U M2",
  "DF": "Ejemplo de conmutador de arista"
};

function openSection(type) {
  currentSection = type;
  document.getElementById("home").classList.add("hidden");
  document.getElementById("section").classList.remove("hidden");
  document.getElementById("sectionTitle").textContent =
    type === "corners" ? "Esquinas" : "Aristas";
  clearResult();
}

function goHome() {
  document.getElementById("section").classList.add("hidden");
  document.getElementById("home").classList.remove("hidden");
}

function searchAlgo() {
  const key = document.getElementById("search").value.toUpperCase();
  const db = currentSection === "corners" ? corners : edges;

  document.getElementById("algo").textContent =
    db[key] || "No encontrado";
}

function clearResult() {
  document.getElementById("search").value = "";
  document.getElementById("algo").textContent = "—";
  document.getElementById("notes").value = "";
}
